# Generated by Django 3.2 on 2021-10-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_module_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(upload_to='uploads/%Y/%m/%d/', verbose_name='Файл'),
        ),
    ]
