# Generated by Django 3.2 on 2021-10-11 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_module_app', '0003_auto_20211008_0137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='calendar',
            options={'verbose_name': 'Заметка', 'verbose_name_plural': 'Заметки'},
        ),
        migrations.AlterField(
            model_name='files',
            name='subject',
            field=models.CharField(choices=[('Парадигмы', 'Парадигмы'), ('Копьютерные сети', 'Копьютерные сети'), ('Человек и компьютер', 'Человек и компьютер'), ('Проектирование програмных систем', 'Проектирование програмных систем'), ('Педагогика и Психология', 'Педагогика и Психология')], max_length=50, verbose_name='Предмет'),
        ),
    ]
